---
title: "data"
author: "Sonya Kalara"
date: "11/27/2018"
output: html_document
---

```{r setup, include=FALSE}
library(haven)
library(fs)
library(readxl)
library(lubridate)
library(kableExtra)
library(janitor)
library(leaflet)
library(statesRcontiguous)
library(ggplot2)
library(sp)
library(rgdal)
library(raster)
library(tidyverse)
library(tigris)
options(tigris_use_cache = TRUE)

newYork <- counties("New York", cb = TRUE)
```

```{r echo = FALSE}
write_rds(newYork, "./FinalApp/newYork.rds") 
hateCrimes <- read_csv("./Hate_Crimes_by_County_and_Bias_Type__Beginning_2010.csv")
pop <- read_excel("population.xlsx")
```

```{r}
dataset <- hateCrimes %>% 
  left_join(pop) %>% 
  mutate(ratio = `Total Incidents` * 10000 / Population) %>%
  arrange(desc(ratio)) 

hcrimes <- dataset %>% 
  write_rds("./FinalApp/dataset.rds")
```
```{r}
table <- dataset %>% 
  filter(`Crime Type` == "Crimes Against Persons") %>% 
          filter(County == "New York") %>% 
  gather(key = "measurement", value = "number", `Anti-Male`:`Anti-Mental Disability`) %>% 
  arrange(desc(number)) %>% 
  select(Year, measurement, number)

plot <- ggplot(table, aes(x=Year, y=number)) + 
  geom_line(aes(group=measurement)) + 
  geom_point(aes(group=measurement)) +
  geom_smooth(method = "lm", se = FALSE)

table
```

